server:
  port: 8080

spring:
  profiles: local
  # mysql
  datasource:
    url: jdbc:mysql://youcheng-test8.mysql.zhangbei.rds.aliyuncs.com/ding_crm_1
    username: youcheng
    password: qTemX6MPAU2P
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      max-lifetime: 3000
  # 缓存
  cache:
    redis:
  # redis
  redis:
    database: 0
    host: 47.92.241.85
    password: Iq8YzsRg2cJcei
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: 3000
        min-idle: 0
        max-idle: 8
  #    lettuce:
  #      pool:
  #        max-active: 8
  #        max-wait: 3000
  #        min-idle: 0
  #        max-idle: 8
  #      shutdown-timeout: 100ms
  # 日志颜色填充
  output:
    ansi:
      enabled: always

# 自定义属性配置类
lab:
  enable: false
  # 宽松绑定
  required_str: abc

